### ISSUE TITLE
慕名而来

### ISSUE THREAD

**Issue by greatming123** [StarInitial/xpcheck#1]
请问怎样支持你的Cos正片呀？

**Comment by threo9** [comment]
同问。

**Comment by ragingvodka** [comment]
同问。

**Comment by StarInitial** [comment]
哈哈哈哈哈哈哈，我就是开个小玩笑~ 
现在的正片都是大学时候拍的，不够好看也不够专业ww
我会加油哒~

**Comment by StarInitial** [comment]
p.s. 
我是男孩子哦，而且目前还没有出过女装cos

**Comment by threo9** [comment]
> 
> 
> 哈哈哈哈哈哈哈，我就是开个小玩笑~
> 现在的正片都是大学时候拍的，不够好看也不够专业ww
> 我会加油哒~

rwkk！（超大声
/Doge
