### ISSUE TITLE
慕名而来膜拜大佬or2

### ISSUE THREAD

**Issue by Xiyumengyin** [StarInitial/xpcheck#10]
同上……可以附上解释之类的比较好，毕竟“母”这个解释还有点多误解什么的都挺容易的……人外等级制度也是可以附张图片之类的。

**Comment by StarInitial** [comment]
我了解你的意思。
实际上我也不是很清楚里面tag的意思，我欣赏作品的承受能力很低，会造成角色身体损伤的作品我看着都会觉得不舒服，我是根据一份文档做出来的，而且没有做任何修改。
只是文档里面也没有标明作者，加上我预期是给朋友玩的。
谁知道我部署在那么垃圾的服务器上的垃圾测试会火起来啊(摔)
