### ISSUE TITLE
建议行为加上主语 比如 你能接受 对 (对方) 电击 吗？ 你能接受对 (你) 电击吗

### ISSUE THREAD

**Issue by Kzsov** [StarInitial/xpcheck#11]

**Comment by Dwscdv3** [comment]
这个测试显然指的对虚拟作品中出现相关要素的接受程度，而虚拟作品很多都是第三人称的（

**Comment by StarInitial** [comment]
我有听说过这方面的建议
其实我在做的时候也有想法，就是这个东西究竟是对自己的还是对象是针对自己所鉴赏的艺术作品的。
我有听过别人说这个设计出来还是针对的作品，毕竟很多东西不可能在现实生活中发生。
也有听过别人对题目以及算法的建议，
然鹅我只是完全按照别人文档的算法做出来的。也就没有打算去调整里面的内容ww

**Comment by sym233** [comment]
> 这个测试显然指的对虚拟作品中出现相关要素的接受程度，而虚拟作品很多都是第三人称的（

我填的时候都带入了现实（

**Comment by Arthropodkiller** [comment]
实际上是特意没有加主语，某些名词本身就包括了主语，而且从来就没有在本子的标签里面看到主语过，因为是针对虚拟作品的，所以提问的应该是你能否接受这样的作品而不是本人。
