### ISSUE TITLE
Dulplicate Questions

### ISSUE THREAD

**Issue by danteehome** [StarInitial/xpcheck#17]
会有问题重复的现象.还没看逻辑也不知道是为什么.

**Comment by Dwscdv3** [comment]
是的，“性转”在题目列表里出现了两次

**Comment by StarInitial** [comment]
应该是我不小心搞重复了

**Comment by sym233** [comment]
@StarInitial 我用ink文件试了一下，没问题
可能是导出的时候有错误，再导出一遍就好了

**Comment by Arthropodkiller** [comment]
在文档里是故意有一些重复的，因为同一个xp会有不同的烈度，所以当然会有不同的等级，不过高分项是应该覆盖掉低分项的

**Comment by StarInitial** [comment]
> 在文档里是故意有一些重复的，因为同一个xp会有不同的烈度，所以肯定会有不同的等级，不过高分项应该是覆盖掉低分项的

确实，毕竟这只是个随手弄出来的玩具Nya~
