### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Arthropodkiller** [StarInitial/xpcheck#2]
不知道作者在制作该测试时有没有参考一个名为“变态等级标准”的文件，那是我在2019年末制作的，感觉找到了志同道合的伙伴，望回复，俺个人介绍里有邮箱

**Comment by greatming123** [comment]
实验一下

**Comment by StarInitial** [comment]
我做的时候完全参考一个叫“性癖调查表”的Excel文件，那是我在群里看见的。
做这个也是因为我一个朋友没有WPS（扶额）
