### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by ClarkWard711** [StarInitial/xpcheck#22]
同inky爱好者，想问问大佬静态网站顶端的restart 保存加载 theme功能怎么实现的啊？

**Comment by StarInitial** [comment]
inky不是自带这种功能了咩！

**Comment by ClarkWard711** [comment]
> inky不是自带这种功能了咩！

啊，我看官方教程文档没找到啊

**Comment by StarInitial** [comment]
就，输出为项目以后打开Html的话，自带这些按钮的
