### ISSUE TITLE
我可以克隆走魔改吗（

### ISSUE THREAD

**Issue by 13756048460** [StarInitial/xpcheck#28]

**Comment by Dwscdv3** [comment]
@StarInitial 好问题，你并未声明许可证（

**Comment by StarInitial** [comment]
改，随便改

**Comment by StarInitial** [comment]
@Dwscdv3 你那部分让不让改你可以自己决定

**Comment by StarInitial** [comment]
我故意没搞许可证的，本身代码冗余度就很高，纯粹赶工做出来的东西，也没花什么精力，内容来源也不是我，许可证什么的算了x

**Comment by Dwscdv3** [comment]
> 我故意没搞许可证的，本身代码冗余度就很高，纯粹赶工做出来的东西，也没花什么精力，内容来源也不是我，许可证什么的算了x

那直接 MIT 或者 [WTFPL](https://github.com/anak10thn/WTFPL/blob/master/LICENSE.txt) 都行（

我那段代码没在文件头注释里声明许可证，默认遵循 repo 根目录 LICENSE

**Comment by StarInitial** [comment]
> > 我故意没搞许可证的，本身代码冗余度就很高，纯粹赶工做出来的东西，也没花什么精力，内容来源也不是我，许可证什么的算了x
> 
> 那直接 MIT 或者 [WTFPL](https://github.com/anak10thn/WTFPL/blob/master/LICENSE.txt) 都行（
> 
> 我那段代码没在文件头注释里声明许可证，默认遵循 repo 根目录 LICENSE

好吧，加上去了喵
