### ISSUE TITLE
第一次玩，有一些问题

### ISSUE THREAD

**Issue by tdgwsqsdgj** [StarInitial/xpcheck#5]
能否把每一个都介绍一下啊，有些只是听过根本不知道实际意义啊，网上搜也搜不太清楚，不过既然是这样我也能得80也是强大到不行了，随便问一下，怎么评分的，我三分之二选的无所谓得几分？

**Comment by ch1ld** [comment]
无聊整理了一下，可能有错作个参考哈

**评分**：满分139分

不接受都是+0

人类级：共24题，满分31分
17题之前： 喜欢/接受/无所谓 +1
17题之后： 喜欢/接受/无所谓 +2

猛兽级：共22题，满分46分
20题之前： 喜欢+2 接受/无所谓+1
20题之后： 喜欢+3 接受/无所谓+2

异形： 共20题，满分62分
19题之前： 喜欢+3 接受/无所谓+2 
第20题： 喜欢+5 接受/无所谓+3

**结语：**
_0~6_ 绵羊级 你对于作品方面的标准仅停留在原始到不能更原始的标准，神知道了精神洁癖的地步，真的是让人叹为观止。

_7~20_ 人类级 你对于作品的标准，处于一种正常且健康的状态，艺术脱胎于现实而超越现实，你勇敢地在作品中寻找着与现实相互交融而不背离的世界。

_21~60_ 勇者级 现实是场无聊的闹剧，它限制了太多想象与可能性，而你在幻想的的世界中自由游荡，作品过激的部分帮你满足现实无法满足的东西。

_61~80_ 巨龙级 正常的作品已经无法满足你，你开始追求那些过于刺激的东西，反正是虚构的，不也挺好的吗。

_81~100_ 异形级 当你凝视深渊的时候，深渊也在凝视着你。

_101~120_ 恶魔级 当你凝视深渊的时候，深渊也看向了你，你们对视了一眼，你脱下了裤子开始打起了飞机，以至于让深渊尴尬地移开了视线。

_121~139_古神级 当你凝视深渊的时候，深渊落荒而逃，而你抓住深渊，把它按在了胯下。
