### ISSUE TITLE
因为在3刷的时候看到新增的附带链接所以就点过来了

### ISSUE THREAD

**Issue by Guderiss** [StarInitial/xpcheck#6]
因为Q群传播，所以火了，属于人传人现象（划掉）

关于得分计算，要不多加一个选项“反感”？
喜欢-接受-无所谓-不接受-反感，这样正负两头对称。
（喜欢=TM社保、接受=可冲、无所谓=有无这个tag不影响我冲或者不冲、不接受=可看但冲不动、反感=别说冲了甚至看不下去）
或许这样的话，LSP们在在选择的时候不那么容易模棱两可......

另外，这个XP测试很棒哦，感谢作者的付出(嗯!)，这个测试正在各个LSPのQ群里绝赞传播中。

“是大佬，我好了！”

**Comment by StarInitial** [comment]
好家伙，并不是大佬，我是无感情的算法搬运机器。
前端我其实非常非常非常菜，甚至赶不上大学生的一般水平。
里面的内容并非我设计的，虽然有些问题我也有所感觉到了，但是为了不改变原有内容作者的意思，我没有进行修改，无论是内容还是算法。

只是没有找到原作者的标注，加上一开始做出来只是给身边几个朋友玩的，所以只标注了算法和内容源于网络。
再一次感谢ww

**Comment by Arthropodkiller** [comment]
不写就是默认反感不加分，讨厌某个选项并不能证明不bt，也有只喜欢某种其他都讨厌的例子，但是不代表他不bt。我们只需要知道某个人有多bt就可以了而不是在某个地方有多正常
