### ISSUE TITLE
24分慕名而来qwq

### ISSUE THREAD

**Issue by SakuraChanNya** [StarInitial/xpcheck#8]
请问可以支持你的Cos嘛？

**Comment by StarInitial** [comment]
啊！！谢谢谢谢！我目前的Cos正片我觉得还不够好~
其实我都清楚，毕竟本身长相没有优势的家伙，也没有很有钱去请特别专业的后期，不管多用心正片也是很不容易有人欣赏的，最多是亲友给个面子点个赞啊什么的。
好像说的有点现实，但是目前我还没能出到我特别满意的作品，所以也就在自己qq空间发过一下下这样子。有我满意的正片或者能成为更专业更好看的Coser我会放出来www
再一次感谢！！
