### ISSUE TITLE
建议加上一些名词解释或者链接到可以解释的网站上

### ISSUE THREAD

**Issue by lilongsky** [StarInitial/xpcheck#9]
有些名词，例如

~~“药渍”，人外（3级）~~

做题的可能并不能理解，进而导致错误选择。

~~不过如果不理解，是不是应该直接选不接受~~

**Comment by bakaflan** [comment]
有一说一，确实。关键词可以鼠标hover上去的时候加一个popout效果，提供文字解释或者相应的图片。
~~如果没看过图完全不知道人外（x级）是什么程度的~~

**Comment by JackZhao98** [comment]
长知识了呢 学到好多新词

**Comment by Arthropodkiller** [comment]
有些词是我自创的词汇，所以网上会找不到。。。其实只要更具自己的理解来就行，就是考虑到会有误差所以总分值做的很大（3.0版本做到了550分左右），这个成绩只能大概描述等级，具体的量化还是做不到的，评分机制实际上并不是非常科学，药渍我也不知道是什么意思，我并不是唯一的文档编辑者，人外是人以外的物种的意思至于后面的几级，记得没错的话应该是是形容物种的猎奇程度的，具体没有划分看你自己。
我解释一些可能需要解释的词汇，人外：人以外的其他物种。双o：前后共同开发。丸吞:整个进入嘴里到变形（超大）木马：是一种木制的锐角三角形的木马，坐在上面会因为重力的关系使得oo，算是一种刑具。o孔：某些巨o的o孔会比较大，利用o孔来进行oo真人也有的。快感转化：把痛觉转化成快感，也可以是a的痛觉转化成b的快感。贯通：下面进来上面出来（超大）。眼o：是用眼眶。
